apiVersion: v1
kind: Service
metadata:
  name: crud-backend-service
spec:
  selector:
    app: crud-backend
  ports:
    - protocol: TCP
      port: 80         # puerto dentro del cluster
      targetPort: 3000 # puerto del contenedor
  type: ClusterIP
